app:
  cookie:
    secure: false
    same-site: Lax

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/rsp
    username: rsp_user
    password: rsp_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발용
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080